### PR TITLE
Less verbose logging

### PR DESCRIPTION
**Pull request by andy-dinger**
I've had a little tidy-up of the mowing and battery level logging as I reckon it was a bit too verbose. Feel free to merge if you agree...

### CODE REVIEW

**Comment by normen** [comment]
Sounds good but the PR has the .gitignore file deleted..

**Comment by andy-dinger** [comment]
> Sounds good but the PR has the .gitignore file deleted..

Oh sorry, my bad! That was a mix-up with DS_Store! I'll try and restore it to the correct version...

**Comment by andy-dinger** [comment]
> > Sounds good but the PR has the .gitignore file deleted..
> 
> Oh sorry, my bad! That was a mix-up with DS_Store! I'll try and restore it to the correct version...

OK, I'm being thick...! How do you undelete/restore a file in a branch?

**Comment by normen** [comment]
It's probably best to just put it back in the folder (grab it from an old branch or copy-paste from the web) and commit that instead of trying to revert anything in the history.

**Comment by andy-dinger** [comment]
Of course MacOS won't let me do that because it thinks .gitignore is a system file! I think I'l have to create a new branch and redo the pull request.

**Pull request closed without merging**
